export default {
    "lote":"TESTE",
    "descricaoLote":"TESTE",
    "design":"",
    "2via":false,
    "diplomas":[
        {
            "IDDIPLOMADO":"",
            "NOMEDIPLOMADO":"",
            "NOME_SOCIAL_DIPLOMADO":null,
            "SEXODIPLOMADO":"",
            "NACIONALIDADEDIPLOMADO":"",
            "CODIGOMUNICIPIONATURALIDADE":"",
            "NOMEMUNICIPIONATURALIDADE":"",
            "UFNATURALIDADE":"",
            "NOME_MUNICIPIO_ESTRANGEIRO":null,
            "TIPO_DOC_OUTRO_DOC_IDENTIFICACAO":null,
            "IDENTIFICADOR_OUTRO_DOC_IDENTIFICACAO":null,
            "CPFNATURALIDADE":"",
            "NUMERORG":"",
            "UFRG":"",
            "ORGAOEXPEDIDORRG":"",
            "DATANASCIMENTORG":"",
            "NOMECURSODADOSCURSO":" ",
            "CODIGOCURSOEMECDADOSCURSO":"",
            "HABILITACAO_DADOS_CURSO":[
                {
                    "NOMEHABILITACAO":"",
                    "DATAHABILITACAO":""
                }
            ],
            "MODALIDADEDADOSCURSO":"",
            "TITULOCONFERIDODADOSCURSO":"",
            "GRAUCONFERIDODADOSCURSO":"",
            "LOGRADOUROENDERECOCURSO":"  ",
            "COMPLEMENTOENDERECOCURSO":"",
            "BAIRROENDERECOCURSO":"",
            "NUMEROENDERECOCURSO":"",
            "CODIGOMUNICIPIOENDERECOCURSO":"",
            "NOMEMUNICIPIOENDERECOCURSO":"",
            "UFENDERECOCURSO":"",
            "CEPENDERECOCURSO":"",
            "TIPOAUTORIZACAO":"",
            "NUMEROAUTORIZACAO":"",
            "DATAAUTORIZACAO":"",
            "VEICULO_PUB_AUTORIZACAO":"",
            "DATA_PUB_AUTORIZACAO":"",
            "SECAO_PUB_AUTORIZACAO":"",
            "PAGINA_PUB_AUTORIZACAO":"",
            "NUM_DOU_AUTORIZACAO":"",
            "TIPORECONHECIMENTO":"",
            "NUMERORECONHECIMENTO":"",
            "DATARECONHECIMENTO":"",
            "DATAPUBRECONHECIMENTO":"",
            "VEICULO_PUB_RECONHECIMENTO":"",
            "NUM_DOU_RECONHECIMENTO":"",
            "NUM_PROCESSO_TRAMITACAO_EMEC_RECONHECIMENTO":null,
            "TIPO_PROCESSO_TRAMITACAO_EMEC_RECONHECIMENTO":null,
            "DATA_CADASTRO_TRAMITACAO_EMEC_RECONHECIMENTO":null,
            "DATA_PROTOCOLO_TRAMITACAO_EMEC_RECONHECIMENTO":null,
            "TIPO_RENOVACAO_RECONHECIMENTO":"",
            "NUM_RENOVACAO_RECONHECIMENTO":"",
            "DATA_RENOVACAO_RECONHECIMENTO":"",
            "VEICULO_PUB_RENOVACAO_RECONHECIMENTO":"",
            "DATA_PUB_RENOVACAO_RECONHECIMENTO":"",
            "SECAO_PUB_RENOVACAO_RECONHECIMENTO":"",
            "PAG_PUB_RENOVACAO_RECONHECIMENTO":"",
            "NUM_DOU_RENOVACAO_RECONHECIMENTO":"",
            "NOMEIESEMISSORA":"",
            "CODIGOMECIESEMISSORA":"",
            "CNPJIESEMISSORA":"",
            "LOGRADOUROENDERECO":" ",
            "NUMEROENDERECO":"",
            "BAIRROENDERECO":"",
            "CODIGOMUNICIPIOENDERECO":"",
            "NOMEMUNICIPIOENDERECO":" ",
            "UFENDERECO":"",
            "CEPENDERECO":"",
            "TIPOCREDENCIAMENTO":"",
            "NUMCREDENCIAMENTO":"",
            "DATACREDENCIAMENTO":"",
            "DATAPUBCREDENCIAMENTO":"",
            "SECAOPUBCREDENCIAMENTO":"",
            "PAGINAPUBCREDENCIAMENTO":"",
            "VEICULO_PUB_CREDENCIAMENTO_IESEMISSORA":"",
            "NUM_DOU_CREDENCIAMENTO_IESEMISSORA":"",
            "TIPORECREDENCIAMENTO":"",
            "NUMRECREDENCIAMENTO":"",
            "DATARECREDENCIAMENTO":"",
            "DATAPUBRECREDENCIAMENTO":"",
            "SECAOPUBRECREDENCIAMENTO":"",
            "PAGINAPUBRECREDENCIAMENTO":"",
            "VEICULO_PUB_RECREDENCIAMENTO_IESEMISSORA":"",
            "NUM_DOU_RECREDENCIAMENTO_IESEMISSORA":"",
            "RAZAOSOCIALMANTENEDORA":"",
            "CNPJMANTENEDORA":"",
            "LOGRADOUROENDMANTENEDORA":"",
            "NUMEROENDMANTENEDORA":"",
            "BAIRROENDMANTENEDORA":"",
            "CODIGOMUNICIPENDMANTENEDORA":"",
            "NOMEMUNICIPIOENDMANTENEDORA":" ",
            "UFENDMANTENEDORA":"",
            "CEPENDMANTENEDORA":"",
            "NOMEIESREGISTRADORA":" ",
            "CODIGOMECIESREGISTRADORA":"",
            "CNPJIESREGISTRADORA":"",
            "LOGRADOURENDIESREGISTRADORA":"",
            "NUMEROENDIESREGISTRADORA":"",
            "BAIRROENDIESREGISTRADORA":"",
            "CODMUNENDIESREGISTRADORA":"",
            "NOMEMUNENDIESREGISTRADORA":"",
            "UFENDIESREGISTRADORA":"",
            "CEPENDIESREGISTRADORA":"",
            "TIPOCREDENCIAMENTOEND":"",
            "NUMCREDENCIAMENTOENDERECO":"",
            "DATACREDENCIAMENTOEND":"",
            "DATAPUBCREDENCIAMENTOEND":"",
            "SECAOPUBCREDENCIAMENTOEND":"",
            "PAGINAPUBCREDENCIAMENTOEND":"",
            "VEICULO_PUB_CREDENCIAMENTO_IESREGISTRADORA":"",
            "NUM_DOU_CREDENCIAMENTO_IESREGISTRADORA":"",
            "TIPORECREDENCIAMENTOCRED":"",
            "NUMRECREDENCIACREDENCIAMENTO":"",
            "DATARECREDENCIACRED":"",
            "DATAPUBRECREDENCIACRED":"",
            "SECAOPUBRECREDENCIACRED":"",
            "PAGINAPUBRECREDENCIACRED":"",
            "VEICULO_PUB_RECREDENCIAMENTO_IESREGISTRADORA":"",
            "NUM_DOU_RECREDENCIAMENTO_IESREGISTRADORA":"",
            "RAZAOSOMANTRECREDENCIAMENTO":"",
            "CNPJMANTRECREDENCIAMENTO":"",
            "LOGRENDMANTRECREDENCIAMENTO":"",
            "NUMENDMANTRECREDENCIAMENTO":"",
            "BAIRENDMANTRECREDENCIAMENTO":"",
            "CODMUNENDMANTRECREDENCIAMENTO":"",
            "NOMEMURECRTIPO":"",
            "NOMEMUENDMANTRECREDENCIAMENTO":"",
            "UFENDMANTRECREDENCIAMENTO":"",
            "CEPENDMANTRECREDENCIAMENTO":"",
            "LIVROREGISTROLIVROREGISTRO":"",
            "NUMFOLHADIPLOMALIVROREGISTRO":"",
            "NUMSEQDIPLOMALIVROREGISTRO":"",
            "PROCESSODIPLOMALIVROREGISTRO":"",
            "DATACOLAGRAULIVROREGISTRO":"",
            "DATAEXPEDDIPLOMALIVROREGISTRO":"",
            "DATAREGDIPLOMALIVROREGISTRO":"",
            "NOMERESPONSAVELREGISTRO":"",
            "CPFRESPONSAVELREGISTRO":"",
            "NUMRARESPONSAVELREGISTRO":"",
            "EMAIL":"",
            "CELULAR":"",
            "DATACONCLUSAOCURSO":"",
            "LIVROREGISTROTERMOCOLACAO":"",
            "FOLHAREGISTROTERMOCOLACAO":"",
            "NUMREGISTROTERMOCOLACAO":"",
            "DATAREGISTROTERMOCOLACAO":"",
            "SECAORECONHECIMENTO":"",
            "PAGINASECAORECONHECIMENTO":"",
            "NOMEPOLO":null,
            "LOGRADOUROENDERECOPOLO":null,
            "NUMEROENDERECOPOLO":null,
            "COMPLEMENTOENDERECOPOLO":null,
            "BAIRROENDERECOPOLO":null,
            "NOMEMUNICIPIOENDERECOPOLO":null,
            "UFENDERECOPOLO":null,
            "CEPENDERECOPOLO":null,
            "CODIGOEMECPOLO":null,
            "CODIGOMUNICIPIOENDERECOPOLO":null,
            "VIA2":"",
            "OBSERVACOES_SEGUNDA_VIA":"",
            "TIPO_INSTITUICAO":"",
            "FUNCAO_RESPONSAVEL":"",
            "TEXTO_MANTENEDORA":"",
            "TEXTO_APOSTILA":"",
            "DocumentacaoAcademica":{
                "DadosPrivadosDiplomado":{
                    "Filiacao":[
                        {
                            "Genitor":{
                                "Nome":"",
                                "NomeSocial":"",
                                "Sexo":"F"
                            }
                        },
                        {
                            "Genitor":{
                                "Nome":"",
                                "NomeSocial":"",
                                "Sexo":""
                            }
                        }
                    ],
                    "HistoricoEscolar":{
                        "CodigoCurriculo":"",
                        "ElementosHistorico":[
                            {
                                "Disciplina":{
                                    "CodigoDisciplina":"",
                                    "NomeDisciplina":"",
                                    "PeriodoLetivo":"",
                                    "CargaHoraria":[
                                        {
                                            "HoraAula":"",
                                            "HoraRelogio":"",
                                            "Etiqueta":""
                                        }
                                    ],
                                    "Nota":"",
                                    "Aprovado":{
                                        "FormaIntegralizacao":""
                                    },
                                    "Docentes":[
                                        {
                                            "Docente":{
                                                "Nome":"",
                                                "Titulacao":"",
                                                "Lattes":"",
                                                "CPF":""
                                            }
                                        }
                                    ]
                                }
                            },
                            {
                                "Disciplina":{
                                    "CodigoDisciplina":"",
                                    "NomeDisciplina":"",
                                    "PeriodoLetivo":"",
                                    "CargaHoraria":[
                                        {
                                            "HoraAula":"",
                                            "HoraRelogio":"",
                                            "Etiqueta":""
                                        }
                                    ],
                                    "Nota":"",
                                    "Aprovado":{
                                        "FormaIntegralizacao":""
                                    },
                                    "Docentes":[
                                        {
                                            "Docente":{
                                                "Nome":"",
                                                "Titulacao":"",
                                                "Lattes":"",
                                                "CPF":""
                                            }
                                        }
                                    ]
                                }
                            },                        
                            {
                                "AtividadeComplementar":{
                                    "CodigoAtividadeComplementar":"",
                                    "DataInicio":"",
                                    "DataFim":"",
                                    "DataRegistro":"",
                                    "TipoAtividadeComplementar":"",
                                    "Descricao":"",
                                    "CargaHorariaEmHoraRelogio":[
                                        {
                                            "HoraRelogio":"",
                                            "Etiqueta":""
                                        }
                                    ],
                                    "DocentesResponsaveisPelaValidacao":{
                                        "Docente":[
                                            {
                                                "Docente":{
                                                    "Nome":"",
                                                    "Titulacao":"",
                                                    "Lattes":"",
                                                    "CPF":""
                                                }
                                            }
                                        ]
                                    }
                                }
                            }
                        ],
                        "DataEmissaoHistorico":"",
                        "HoraEmissaoHistorico":"",
                        "SituacaoAluno":"",
                        "SituacaoDiscente":{
                            "PeriodoLetivo":"",
                            "Formado":{
                                "DataColacaoGrau":"",
                                "DataConclusaoCurso":"",
                                "DataExpedicaoDiploma":""
                            }
                        },
                        "SituacaoAtualDiscente":{
                            "PeriodoLetivo":"",
                            "Formado":{
                                "DataColacaoGrau":"",
                                "DataConclusaoCurso":"",
                                "DataExpedicaoDiploma":""
                            }
                        },
                        "ENADE":[
                            {
                                "NaoHabilitado":{
                                    "Condicao":"",
                                    "Edicao":"",
                                    "OutroMotivo":""
                                }
                            }
                        ],
                        "DataProvaEnade":"",
                        "CargaHorariaCursoIntegralizada":{
                            "HoraAula":"",
                            "HoraRelogio":""
                        },
                        "CargaHorariaCurso":{
                            "HoraAula":"",
                            "HoraRelogio":""
                        },
                        "IngressoCurso":{
                            "Data":"",
                            "FormaAcesso":"",
                            "DataConclusao":""
                        }
                    }
                },
                "TermoResponsabilidadeEmissora":{
                    "Nome":"",
                    "CPF":"",
                    "Cargo":"",
                    "AtoDesignacao":""
                },
                "DocumentacaoComprobatoria":[
                    {
                        "Documento":{
                            "tipo":"",
                            "observacoes":"",
                            "base64":""
                        }
                    },
                    {
                        "Documento":{
                            "tipo":"",
                            "observacoes":"",
                            "base64":""
                        }
                    }
                ]
            },
            "HistoricoEscolar":{
                "Aluno":{
                    "ID":"",
                    "Nome":"",
                    "NomeSocial":"",
                    "Sexo":"",
                    "Nacionalidade":"",
                    "Naturalidade":{
                        "CodigoMunicipio":"",
                        "NomeMunicipio":"",
                        "UF":""
                    },
                    "CPF":"",
                    "RG":{
                        "Numero":"",
                        "UF":"",
                        "OrgaoExpedidor":""
                    },
                    "DataNascimento":""
                },
                "DadosCurso":{
                    "NomeCurso":"",
                    "CodigoCursoEMEC":"",
                    "SemCodigoCursoEMEC":{
                        "NumeroProcesso":"",
                        "TipoProcesso":"",
                        "DataCadastro":"",
                        "DataProtocolo":""
                    },
                    "Habilitacao":[
                        {
                            "Habilitacao":{
                                "NomeHabilitacao":"",
                                "DataHabilitacao":""
                            }
                        }
                    ],
                    "TituloConferido":{
                        "Titulo":""
                    },
                    "CargaHorariaExigidaAtividadeComplementar":"",
                    "Autorizacao":{
                        "Tipo":"",
                        "Numero":"",
                        "Data":"",
                        "VeiculoPublicacao":"",
                        "DataPublicacao":"",
                        "SecaoPublicacao":"",
                        "PaginaPublicacao":"",
                        "NumeroDOU":"",
                        "InformacoesTramitacaoEMEC":{
                            "NumeroProcesso":"",
                            "TipoProcesso":"",
                            "DataCadastro":"",
                            "DataProtocolo":""
                        }
                    },
                    "Reconhecimento":{
                        "Tipo":"",
                        "Numero":"",
                        "Data":"",
                        "VeiculoPublicacao":"",
                        "DataPublicacao":"",
                        "SecaoPublicacao":"",
                        "PaginaPublicacao":"",
                        "NumeroDOU":"",
                        "InformacoesTramitacaoEMEC":{
                            "NumeroProcesso":"",
                            "TipoProcesso":"",
                            "DataCadastro":"",
                            "DataProtocolo":""
                        }
                    },
                    "RenovacaoReconhecimento":{
                        "Tipo":"",
                        "Numero":"",
                        "Data":"",
                        "VeiculoPublicacao":"",
                        "DataPublicacao":"",
                        "SecaoPublicacao":"",
                        "PaginaPublicacao":"",
                        "NumeroDOU":"",
                        "InformacoesTramitacaoEMEC":{
                            "NumeroProcesso":"",
                            "TipoProcesso":"",
                            "DataCadastro":"",
                            "DataProtocolo":""
                        }
                    }
                },
                "IesEmissora":{
                    "Nome":"",
                    "CodigoMEC":"",
                    "CNPJ":"",
                    "Endereco":{
                        "Logradouro":"",
                        "Numero":"",
                        "Complemento":"",
                        "Bairro":"",
                        "CodigoMunicipio":"",
                        "NomeMunicipio":"",
                        "UF":"",
                        "CEP":""
                    },
                    "Credenciamento":{
                        "Tipo":"",
                        "Numero":"",
                        "Data":"",
                        "VeiculoPublicacao":"",
                        "DataPublicacao":"",
                        "SecaoPublicacao":"",
                        "PaginaPublicacao":"",
                        "NumeroDOU":""
                    },
                    "Recredenciamento":{
                        "Tipo":"",
                        "Numero":"",
                        "Data":"",
                        "VeiculoPublicacao":"",
                        "DataPublicacao":"",
                        "SecaoPublicacao":"",
                        "PaginaPublicacao":"",
                        "NumeroDOU":"",
                        "InformacoesTramitacaoEMEC":{
                            "NumeroProcesso":"",
                            "TipoProcesso":"",
                            "DataCadastro":"",
                            "DataProtocolo":""
                        }
                    },
                    "RenovacaoDeRecredenciamento":{
                        "Tipo":"",
                        "Numero":"",
                        "Data":"",
                        "VeiculoPublicacao":"",
                        "DataPublicacao":"",
                        "SecaoPublicacao":"",
                        "PaginaPublicacao":"",
                        "NumeroDOU":"",
                        "InformacoesTramitacaoEMEC":{
                            "NumeroProcesso":"",
                            "TipoProcesso":"",
                            "DataCadastro":"",
                            "DataProtocolo":""
                        }
                    },
                    "Mantenedora":{
                        "RazaoSocial":"",
                        "CNPJ":"",
                        "Endereco":{
                            "Logradouro":"",
                            "Numero":"",
                            "Complemento":"",
                            "Bairro":"",
                            "CodigoMunicipio":"",
                            "NomeMunicipio":"",
                            "NomeMunicipioEstrangeiro":"",
                            "UF":"",
                            "CEP":""
                        }
                    },
                    "NomeMunicipioIesEmissora":"",
                    "UFIesEmissora":"",
                    "AutorizacaoIesEmissora":"",
                    "CredenciamentoIesEmissora":"",
                    "ResponsavelHistorico":"",
                    "CargoResponsavelHistorico":"",
                    "Observacao":""
                },
                "HistoricoEscolar":{
                    "CodigoCurriculo":"",
                    "ElementosHistorico":[
                        {
                            "Disciplina":{
                                "CodigoDisciplina":"",
                                "NomeDisciplina":"",
                                "PeriodoLetivo":"",
                                "CargaHoraria":[
                                    {
                                        "HoraAula":"",
                                        "HoraRelogio":"",
                                        "Etiqueta":""
                                    }
                                ],
                                "Nota":"",
                                "Aprovado":{
                                    "FormaIntegralizacao":""
                                },
                                "Docentes":[
                                    {
                                        "Docente":{
                                            "Nome":"",
                                            "Titulacao":"",
                                            "Lattes":"",
                                            "CPF":""
                                        }
                                    }
                                ]
                            }
                        },
                        {
                            "Disciplina":{
                                "CodigoDisciplina":"",
                                "NomeDisciplina":" ",
                                "PeriodoLetivo":"",
                                "CargaHoraria":[
                                    {
                                        "HoraAula":"",
                                        "HoraRelogio":"",
                                        "Etiqueta":""
                                    }
                                ],
                                "Nota":"",
                                "Aprovado":{
                                    "FormaIntegralizacao":""
                                },
                                "Docentes":[
                                    {
                                        "Docente":{
                                            "Nome":"",
                                            "Titulacao":"",
                                            "Lattes":"",
                                            "CPF":""
                                        }
                                    }
                                ]
                            }
                        },
                        {
                            "AtividadeComplementar":{
                                "CodigoAtividadeComplementar":"",
                                "DataInicio":"",
                                "DataFim":"",
                                "DataRegistro":"",
                                "TipoAtividadeComplementar":"",
                                "Descricao":"",
                                "CargaHorariaEmHoraRelogio":[
                                    {
                                        "HoraRelogio":"",
                                        "Etiqueta":""
                                    }
                                ],
                                "DocentesResponsaveisPelaValidacao":{
                                    "Docente":[
                                        {
                                            "Docente":{
                                                "Nome":"",
                                                "Titulacao":"",
                                                "Lattes":"",
                                                "CPF":""
                                            }
                                        }
                                    ]
                                }
                            }
                        }
                    ],
                    "DataEmissaoHistorico":"",
                    "SituacaoAluno":"",
                    "SituacaoDiscente":{
                        "PeriodoLetivo":"",
                        "Formado":{
                            "DataColacaoGrau":"",
                            "DataConclusaoCurso":"",
                            "DataExpedicaoDiploma":""
                        }
                    },
                    "SituacaoAtualDiscente":{
                        "PeriodoLetivo":"",
                        "Formado":{
                            "DataColacaoGrau":"",
                            "DataConclusaoCurso":"",
                            "DataExpedicaoDiploma":""
                        }
                    },
                    "ENADE":[
                        {
                            "NaoHabilitado":{
                                "Condicao":"",
                                "Edicao":"",
                                "OutroMotivo":""
                            }
                        }
                    ],
                    "DataProvaEnade":"",
                    "CargaHorariaCursoIntegralizada":{
                        "HoraAula":"",
                        "HoraRelogio":""
                    },
                    "CargaHorariaCurso":{
                        "HoraAula":"",
                        "HoraRelogio":""
                    },
                    "IngressoCurso":{
                        "Data":"",
                        "FormaAcesso":"",
                        "DataConclusao":""
                    }
                },
                "Urlhistorico":""
            }
        }
    ]
};
